default_avatar: "rails.png"
number_description_truncate: 50
number_user_in_list: 10
number_word_in_lessons: 20
number_answers: 4
size_image_of_word: 60
activity:
  follow: "follow"
  unfollow: "unfollow"
  learned: "learned"
  learning: "learning"
option:
  - all_word
  - learned
  - no_learn
follow_methods:
  - following
  - followers
